version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" # so local Next.js can connect
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # This is for CI/staging or when you want the app in Docker
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
